print('Задача 1')
print(60*60)
print('Задача 2')
seconds_per_hour = (60*60)
print (60*60)
print('Задача 3')
seconds_per_day = (60* 60 * 24)
print(seconds_per_day)
print('Задача 4')
seconds_per_day = (seconds_per_hour) * 24
print (seconds_per_day)
print('Задача 5')
print(seconds_per_day/seconds_per_hour)
print('Задача 6')
print(seconds_per_day//seconds_per_hour)
print('Задача 7')
print(7+5)
print (144//12)
print (19-7)
print(3*4)
print('Задача 8')
number = '9'
print('The best number is - '+ number)
print('Задача 9')
name = 'Sonya'
print(str. Lower (name))
print(str.upper(name))
print(str. swapcase (name))
